import json
from web3 import Web3

w3 = Web3(Web3.HTTPProvider("hardhat_node"))

assert w3.is_connected(), "Connection to hardhat failed "

account = w3.eth.accounts[0]
print("Account used for deploy:", account)

# Load ABI + bytecode generated by Hardhat
with open("artifacts/contracts/DocumentRegistry.sol/DocumentRegistry.json") as f:
    artifact = json.load(f)

abi = artifact["abi"]
bytecode = artifact["bytecode"]

DocumentRegistry = w3.eth.contract(abi=abi, bytecode=bytecode)

tx_hash = DocumentRegistry.constructor().transact({"from": account})

tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

print(f"Contract DocumentRegistry deployed to: {tx_receipt.contractAddress}")
